"""Pluggable algorithm base class and loader.

Algorithms are Python files in backend/algos/ that extend the Algorithm base class.
The AlgoManager watches the directory and hot-reloads new/modified algos.
"""

import importlib
import importlib.util
import logging
import os
from abc import ABC, abstractmethod
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

import pandas as pd

logger = logging.getLogger("terminal.algos")

ALGOS_DIR = Path(__file__).parent


@dataclass
class Signal:
    """Trade signal generated by an algorithm."""
    symbol: str
    side: str          # BUY or SELL
    strength: float    # 0.0 to 1.0
    price: float
    stop_loss: float = 0.0
    take_profit: float = 0.0
    reasons: list = None

    def __post_init__(self):
        if self.reasons is None:
            self.reasons = []

    def to_dict(self) -> dict:
        return {
            "symbol": self.symbol,
            "side": self.side,
            "strength": self.strength,
            "price": self.price,
            "stop_loss": self.stop_loss,
            "take_profit": self.take_profit,
            "reasons": self.reasons,
        }


class Algorithm(ABC):
    """Base class for all trading algorithms.

    To create a new algorithm:
    1. Create a .py file in backend/algos/
    2. Define a class that extends Algorithm
    3. Set name, markets, and frequency
    4. Implement generate_signals()
    """

    name: str = "Unnamed Algorithm"
    description: str = ""
    markets: list[str] = ["stocks"]      # stocks, crypto, forex, etf
    frequency: str = "lft"               # hft, mft, lft
    version: str = "1.0.0"
    enabled: bool = True
    parameters: dict = {}

    @abstractmethod
    def generate_signals(self, df: pd.DataFrame, params: dict = None) -> list[Signal]:
        """Generate trading signals from OHLCV dataframe.

        Args:
            df: DataFrame with columns: open, high, low, close, volume
            params: Runtime parameters (overrides self.parameters)

        Returns:
            List of Signal objects.
        """
        pass

    def validate(self, df: pd.DataFrame) -> bool:
        """Validate that the data is suitable for this algorithm."""
        required = {"open", "high", "low", "close", "volume"}
        return required.issubset(set(df.columns)) and len(df) >= 20

    def to_dict(self) -> dict:
        return {
            "name": self.name,
            "description": self.description,
            "markets": self.markets,
            "frequency": self.frequency,
            "version": self.version,
            "enabled": self.enabled,
            "parameters": self.parameters,
        }


class AlgoManager:
    """Load, manage, and hot-reload trading algorithms."""

    def __init__(self):
        self.algos: dict[str, Algorithm] = {}
        self._load_all()

    def _load_all(self):
        """Scan algos directory and load all algorithm files."""
        for path in ALGOS_DIR.glob("*.py"):
            if path.name.startswith("_"):
                continue
            self._load_file(path)
        logger.info("Loaded %d algorithms", len(self.algos))

    def _load_file(self, path: Path):
        """Load a single algorithm file."""
        try:
            spec = importlib.util.spec_from_file_location(path.stem, path)
            mod = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(mod)

            for attr_name in dir(mod):
                attr = getattr(mod, attr_name)
                if (
                    isinstance(attr, type)
                    and issubclass(attr, Algorithm)
                    and attr is not Algorithm
                ):
                    instance = attr()
                    self.algos[instance.name] = instance
                    logger.info("Loaded algo: %s (v%s)", instance.name, instance.version)
        except Exception as exc:
            logger.error("Failed to load algo from %s: %s", path, exc)

    def reload(self):
        """Hot-reload all algorithms."""
        self.algos.clear()
        self._load_all()

    def list_algos(self) -> list[dict]:
        return [algo.to_dict() for algo in self.algos.values()]

    def toggle(self, name: str, enabled: bool) -> dict:
        if name in self.algos:
            self.algos[name].enabled = enabled
            return {"success": True, "name": name, "enabled": enabled}
        return {"error": f"Algorithm '{name}' not found"}

    def run_algo(self, name: str, df: pd.DataFrame, params: dict = None) -> list[dict]:
        algo = self.algos.get(name)
        if not algo:
            return [{"error": f"Algorithm '{name}' not found"}]
        if not algo.enabled:
            return [{"error": f"Algorithm '{name}' is disabled"}]
        if not algo.validate(df):
            return [{"error": "Invalid data for this algorithm"}]

        signals = algo.generate_signals(df, params)
        return [s.to_dict() for s in signals]
